Q4-a :
	python -W ignore naiveBayes.py

Q4-b :
	python -W ignore gmm.py

Q10-a :
	python -W ignore perceptron.py Single

Q10-b :
	python -W ignore perceptron.py Batch

Q11-a :
	python -W ignore relaxationUpdatePerceptron.py Single

Q11-b :
	python -W ignore relaxationUpdatePerceptron.py Batch

full :
	python -W ignore relaxationUpdatePerceptron.py Batch
	python -W ignore relaxationUpdatePerceptron.py Single
	python -W ignore perceptron.py Batch
	python -W ignore perceptron.py Single
	python -W ignore naiveBayes.py
	python -W ignore gmm.py
