Q4-a :
	python -W ignore naiveBayes.py
	$(MAKE) remove

Q4-b :
	python -W ignore gmm.py
	$(MAKE) remove

Q10 :
	python -W ignore perceptron.py
	$(MAKE) remove

Q11 :
	python -W ignore relaxationUpdatePerceptron.py
	$(MAKE) remove

full :
	python -W ignore relaxationUpdatePerceptron.py
	python -W ignore perceptron.py
	python -W ignore naiveBayes.py
	python -W ignore gmm.py
	$(MAKE) remove
	
remove :
	rm -f *.pyc